# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/min-sklearn',
                'doc_host': 'https://xiaochuany.github.io',
                'git_url': 'https://github.com/xiaochuany/min-sklearn',
                'lib_path': 'min_sklearn'},
  'syms': { 'min_sklearn.metrics': { 'min_sklearn.metrics.accuracy_score': ('metrics.html#accuracy_score', 'min_sklearn/metrics.py'),
                                     'min_sklearn.metrics.f1_score': ('metrics.html#f1_score', 'min_sklearn/metrics.py'),
                                     'min_sklearn.metrics.precision_recall_fscore': ( 'metrics.html#precision_recall_fscore',
                                                                                      'min_sklearn/metrics.py'),
                                     'min_sklearn.metrics.precision_score': ('metrics.html#precision_score', 'min_sklearn/metrics.py'),
                                     'min_sklearn.metrics.recall_score': ('metrics.html#recall_score', 'min_sklearn/metrics.py')}}}
