# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/min-sklearn',
                'doc_host': 'https://xiaochuany.github.io',
                'git_url': 'https://github.com/xiaochuany/min-sklearn',
                'lib_path': 'min_sklearn'},
  'syms': {'min_sklearn.core': {'min_sklearn.core.foo': ('core.html#foo', 'min_sklearn/core.py')}}}
